"use client";
import { useEffect, useState } from "react";
import PageShell from "@/components/PageShell";
import GarmentImage from "@/components/GarmentImage";
import RevampPreview from "@/components/RevampPreview";
import Modal from "@/components/Modal";
import { useWardrobe } from "@/components/WardrobeProvider";
import { clutterScore } from "@/lib/scoring";
import { postJson, sourceLabel } from "@/lib/client-api";
import donations from "@/data/donations.json";

import type { Garment, RevampResponse, ListingResponse } from "@/types";
type Flow = { garment: Garment; mode: "revamp" | "sell" | "donate" };

function CircularFlow({ flow, close }: { flow: Flow; close: () => void }) {
  const { data,status }=useWardrobe();const g=data!.closet.find(item=>item.id===flow.garment.id)!;
  const [idea,setIdea]=useState<number|null>(null);const [message,setMessage]=useState("");const [condition,setCondition]=useState("Condition to be confirmed");
  const [revamp,setRevamp]=useState<RevampResponse|null>(null);const [listingData,setListing]=useState<ListingResponse|null>(null);const [busy,setBusy]=useState(false);const [failure,setFailure]=useState("");const [retry,setRetry]=useState(0);
  useEffect(()=>{if(flow.mode==="donate")return;let cancelled=false;const load=async()=>{setBusy(true);setFailure("");setIdea(null);try{if(flow.mode==="revamp"){const response=await postJson<RevampResponse>("/api/revamp",{garment:flow.garment});if(!cancelled)setRevamp(response);}else{const response=await postJson<ListingResponse>("/api/listing",{garment:flow.garment,condition});if(!cancelled)setListing(response);}}catch(error){if(!cancelled)setFailure(error instanceof Error?error.message:"Could not generate a result. Please try again.");}finally{if(!cancelled)setBusy(false);}};void load();return()=>{cancelled=true;};},[flow.garment,flow.mode,condition,retry]);
  const ideas=revamp?.ideas??[];const chosen=idea===null?null:ideas[idea];
  const listing=listingData?`${listingData.title}\n\nSuggested price: ${listingData.suggestedPriceRange}\n\n${listingData.description}\nCondition: ${listingData.condition}\n\n${listingData.keywords.map(k=>"#"+k.replaceAll(" ","")).join(" ")}`:"";
  const bag=data!.closet.filter(item=>item.status==="donate");
  return <Modal title={flow.mode==="revamp"?(chosen?"Today’s DIY":"Give it another life"):flow.mode==="sell"?"Ready for its next closet?":"Pass it forward"} onClose={close}>
    <div className="mb-6 flex items-center gap-5"><GarmentImage garment={g} className="aspect-square w-28 shrink-0"/><div><p className="eyebrow mb-2">{flow.mode==="revamp"?"Revamp":"Circular fashion"}</p><h3 className="font-serif text-2xl">{g.name}</h3><p className="mt-2 text-xs capitalize text-stone-500">{g.material} · {g.color}</p></div></div>
    {busy&&<p role="status" className="py-8 text-center text-sm">Generating {flow.mode=== "revamp"?"DIY ideas":"your listing"}…</p>}{failure&&<div role="alert" className="my-4 text-sm"><p>{failure}</p><button className="btn-secondary mt-3" onClick={()=>setRetry(n=>n+1)}>Try again</button></div>}{flow.mode==="revamp" && !busy && !failure && <><span className="demo-label mb-5">{sourceLabel(revamp)} · choose what suits your piece</span>{!chosen?<div className="space-y-3">{ideas.map((option,i)=><article key={JSON.stringify([g.id,option])} className="rounded-2xl bg-white p-5"><h3 className="font-serif text-2xl">{option.title}</h3><p className="mt-2 text-xs text-stone-500">{option.timeMinutes} min · {option.difficulty}</p><p className="mt-3 text-sm leading-5 text-stone-600">{option.description}</p><RevampPreview compact garment={g} idea={option}/><button onClick={()=>setIdea(i)} className="mt-3 min-h-10 text-xs underline underline-offset-4">View DIY instructions ↗</button></article>)}</div>:<div><button onClick={()=>setIdea(null)} className="mb-5 min-h-10 text-xs underline">← All ideas</button><h3 className="font-serif text-3xl">{chosen.title}</h3><p className="my-3 text-xs text-stone-500">{chosen.timeMinutes} min / {chosen.difficulty}</p><RevampPreview key={JSON.stringify([g.id,chosen])} garment={g} idea={chosen}/><p className="eyebrow mt-6">Materials</p><p className="mt-2 text-sm leading-6">{chosen.materials.join(" · ")}</p><ol className="my-6 list-decimal space-y-4 pl-5 text-sm leading-6">{chosen.steps.map(step=><li key={step}>{step}</li>)}</ol><button disabled={g.status==="revamp"} onClick={()=>{status(g.id,"revamp",chosen.title);setMessage("Revamp started. This piece is now in your revamp queue.");}} className="btn-primary w-full">{g.status==="revamp"?"Revamp started":"Start revamp"}</button></div>}</>}
    {flow.mode==="sell" && !busy && !failure && listingData && <><p className="demo-label mb-5">{sourceLabel(listingData)} · review details before sharing</p><label className="mb-4 block text-xs text-stone-500">Condition<select value={condition} onChange={e=>setCondition(e.target.value)} className="mt-2 block w-full rounded-xl bg-white p-3 text-sm text-stone-900"><option>Condition to be confirmed</option><option>New with tags</option><option>Excellent used condition</option><option>Good used condition</option><option>Visible wear — describe flaws before sharing</option></select></label><div className="rounded-2xl bg-white p-6"><p className="eyebrow">Suggested price</p><p className="my-2 font-serif text-4xl">{listingData.suggestedPriceRange}</p><p className="text-xs text-stone-500">Price is an estimate. Confirm brand, condition, and resale value.</p><pre className="mt-6 whitespace-pre-wrap font-sans text-sm leading-6">{listing}</pre></div><div className="mt-5 flex flex-wrap gap-3"><button onClick={async()=>{try{await navigator.clipboard.writeText(listing);setMessage("Listing copied.");if(g.status!=="sold")status(g.id,"sell");}catch{setMessage("Clipboard unavailable. Select the listing text above to copy it manually.");}}} className="btn-primary">Copy listing</button><button disabled={g.status==="sold"} onClick={()=>{status(g.id,"sold");setMessage("Marked as sold. Another closet, a new chapter.");}} className="btn-secondary">{g.status==="sold"?"Sold":"Mark as sold"}</button></div></>}
    {flow.mode==="donate" && <><div className="rounded-2xl bg-white p-6"><p className="eyebrow mb-3">Donation bag</p><p className="font-serif text-4xl">{bag.length} {bag.length===1?"piece":"pieces"}</p><p className="mt-2 text-sm text-stone-500">Ready for another life.</p><div className="mt-4 flex flex-wrap gap-2">{Object.entries(bag.reduce<Record<string,number>>((counts,item)=>({...counts,[item.category]:(counts[item.category]??0)+1}),{})).map(([category,count])=><span key={category} className="rounded-full bg-stone-100 px-3 py-2 text-xs capitalize">{category}: {count}</span>)}</div></div><p className="eyebrow mb-3 mt-6">Places to explore</p><div className="space-y-3">{donations.map(resource=><div key={resource.id} className="rounded-2xl bg-white p-4"><h3 className="text-sm font-medium">{resource.name}</h3><p className="mt-2 text-xs leading-5 text-stone-500">{resource.description}</p></div>)}</div><button disabled={g.status==="donate"||g.status==="donated"} onClick={()=>{status(g.id,"donate");setMessage("Added to your donation bag.");}} className="btn-primary mt-6 w-full">{g.status==="donate"?"In your donation bag":g.status==="donated"?"Donated":"Add to donation bag"}</button></>}
    <p role="status" className="mt-4 text-sm leading-6 text-stone-600">{message}</p><p className="mt-3 text-xs text-stone-500">{(flow.mode==="revamp"?revamp:listingData)?.notice}</p>
  </Modal>;
}
export default function ClutterPage(){const {data,status,addDemoHistory}=useWardrobe();const [flow,setFlow]=useState<Flow|null>(null);const [message,setMessage]=useState("");const active=data?.closet.filter(g=>g.status==="active"||g.status==="clutter")??[];const candidates=active.filter(g=>clutterScore(g,data?.interactions).candidate).sort((a,b)=>clutterScore(b,data?.interactions).score-clutterScore(a,data?.interactions).score);const queue=data?.closet.filter(g=>["revamp","sell","donate"].includes(g.status))??[];return <PageShell label="Your clutter" title="Room for a new chapter." subtitle="These pieces keep getting left behind." aside={<span className="demo-label">Your recorded behavior</span>}>
  <div className="mb-8 flex flex-wrap items-center justify-between gap-5 rounded-3xl bg-white p-6"><div><span className="metric">{candidates.length}</span><span className="eyebrow ml-4">Pieces need attention</span></div></div>
  <p className="mb-7 max-w-2xl text-sm leading-6 text-stone-500">Pieces shown at least 4 times and rejected or swapped at least 70% of the time appear here. Direct swaps are stronger evidence; locks and recorded wears reduce the score. You decide what happens next.</p>
  <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{candidates.map(g=><article key={g.id} className="rounded-3xl bg-white p-4"><GarmentImage garment={g} className="aspect-square"/><h2 className="mt-5 min-h-10 text-sm font-medium">{g.name}</h2><div className="my-4 grid grid-cols-3 gap-2 text-center">{[["Shown",g.timesShown],["Rejected",g.timesRejected],["Worn",g.timesWorn]].map(([label,n])=><div key={label}><p className="font-serif text-2xl">{n}</p><p className="mt-1 text-[9px] uppercase tracking-wide text-stone-500">{label}</p></div>)}</div><p className="text-xs leading-5 text-stone-500">Clutter score: {clutterScore(g,data?.interactions).score}/100</p><ul className="mt-3 space-y-1 text-xs leading-5 text-stone-500">{clutterScore(g,data?.interactions).reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><div className="mt-5 flex flex-wrap gap-1.5">{(["revamp","sell","donate"] as const).map(mode=><button key={mode} onClick={()=>setFlow({garment:g,mode})} className={`min-h-11 flex-1 rounded-full px-3 text-[9px] uppercase tracking-wider ${mode==="revamp"?"bg-stone-900 text-white":"bg-stone-100"}`}>{mode}</button>)}</div></article>)}</div>
  {!candidates.length&&<div className="rounded-3xl bg-white p-12 text-center"><h2 className="font-serif text-3xl">Nothing needs a decision right now.</h2><p className="mt-3 text-sm text-stone-500">Keep exploring your fits. If your saved wardrobe predates the demo history, you can add seed history below without replacing your items or decisions.</p><button className="btn-secondary mt-5" onClick={()=>{addDemoHistory();setMessage("Demo history added to matching pieces. Existing garments and decisions were preserved.");}}>Add demo history to my wardrobe</button></div>}
  {!!queue.length&&<section className="mt-12"><h2 className="font-serif text-3xl">Your next chapters</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{queue.map(g=><div key={g.id} className="flex flex-wrap items-center gap-4 rounded-2xl bg-white p-4"><GarmentImage garment={g} className="size-20"/><div className="flex-1"><p className="eyebrow">{g.status==="donate"?"Donation bag":g.status}</p><h3 className="mt-2 text-sm">{g.name}</h3></div><div className="flex flex-wrap gap-2"><button onClick={()=>setFlow({garment:g,mode:g.status as "revamp"|"sell"|"donate"})} className="min-h-10 px-2 text-xs underline">Continue</button><button onClick={()=>{status(g.id,"active");setMessage("Returned to your active closet.");}} className="min-h-10 px-2 text-xs underline">Keep in closet</button>{g.status==="donate"&&<button onClick={()=>{status(g.id,"donated");setMessage("Donation recorded. Thank you for passing it forward.");}} className="min-h-10 px-2 text-xs underline">Mark donated</button>}</div></div>)}</div></section>}
  <p role="status" className="mt-5 text-sm text-stone-600">{message}</p><p className="mt-12 text-center text-[10px] uppercase leading-6 tracking-widest text-stone-500">Rewear → Restyle → Revamp → Resell → Donate → Recycle when necessary</p>
  {flow&&<CircularFlow key={`${flow.garment.id}-${flow.mode}`} flow={flow} close={()=>setFlow(null)}/>}
</PageShell>;}
