import type { Garment } from "@/types";
export interface RevampIdea { title: string; time: string; difficulty: string; materials: string[]; steps: string[] }
export function revampIdeas(g: Garment): RevampIdea[] {
  const garment = ["top","bottom","dress","outerwear"].includes(g.category);
  const soft = garment || g.id.includes("scarf") || g.id.includes("beanie");
  return [
    {title: garment?"A new silhouette":soft?"The folded edit":"The charm edit",time:"15 min",difficulty:"Easy",materials:garment?["Removable styling clips","Mirror"]:soft?["Mirror","Soft fabric tie"]:["Removable charm","Compatible clasp"],steps:garment?["Try the piece on over a familiar outfit.","Fold the hem inward or gather a small section at the waist.","Secure from the inside using removable styling clips; avoid delicate fabric.","Move and sit to check the fit. Remove clips before washing."]:soft?["Lay the piece on a clean surface.","Try a narrower fold or a new cuff to change its proportions.","Secure loosely with a soft tie if needed.","Pair with a neutral outfit and adjust for comfort."]:["Inspect a sturdy loop or attachment point.","Choose a lightweight removable charm that fits the hardware.","Attach without puncturing or gluing the item.","Check that closures and movement remain unobstructed."]},
    {title:soft?"A little embroidery":"A polished refresh",time:"35 min",difficulty:"Medium",materials:soft?["Scrap fabric","Embroidery thread","Needle","Small hoop"]:["Material-appropriate cleaning cloth","Care instructions"],steps:soft?["Check the care label; skip leather, coated, and delicate fabrics.","Practice a tiny motif on scrap fabric first.","Choose a low-stress area and stitch a small tonal detail.","Secure the thread on the reverse and gently press only if the label allows."]:["Read the care instructions before choosing a product.","Test on a hidden area and let it dry.","Clean gently with a suitable cloth; avoid soaking hardware.","Let the item dry fully and style it with a familiar outfit."]},
    {title:garment?"The tailored edit":"A fresh detail",time:"30 min planning",difficulty:"Medium",materials:["Measuring tape","Notebook","Reference photo"],steps:["Try the piece with two outfits you already love.","Note one detail that keeps you from wearing it.","Sketch a small alteration or removable detail. Avoid irreversible cuts.","For structural changes, ask a tailor or repair specialist to assess the material before starting."]},
  ];
}
