"use client";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import GarmentImage from "@/components/GarmentImage";
import { useWardrobe } from "@/components/WardrobeProvider";
import { type ShoppingResult } from "@/types";
import { CANDIDATE_ID } from "@/lib/shop-analysis";
import { prepareImage, type PreparedImage } from "@/lib/upload";
import { postJson, sourceLabel } from "@/lib/client-api";
import type { GarmentCategory, GarmentFormality, ShopAnalysis } from "@/types";
const categories: [GarmentCategory,string][]=[["top","Top"],["bottom","Bottom"],["dress","Dress"],["outerwear","Outerwear"],["shoes","Shoes"],["bag","Bag"],["accessory","Accessory"]];
export default function ShopPage(){
 const {data,saveShopping}=useWardrobe();const upload=useRef<HTMLInputElement>(null);const camera=useRef<HTMLInputElement>(null);
 const [preview,setPreview]=useState("");const [fileName,setFileName]=useState("");const [category,setCategory]=useState<GarmentCategory>("outerwear");const [result,setResult]=useState<ShoppingResult|null>(null);const [error,setError]=useState("");const [showLooks,setShowLooks]=useState(false);const [alternatives,setAlternatives]=useState(false);const [dragging,setDragging]=useState(false);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 const [prepared,setPrepared]=useState<PreparedImage|null>(null);const [busy,setBusy]=useState(false);const [color,setColor]=useState("black");const [formality,setFormality]=useState<GarmentFormality>("smart-casual");const [style,setStyle]=useState("minimal");
 async function accept(file?:File){if(!file)return;setBusy(true);setPrepared(null);setError("");try{const image=await prepareImage(file);setPrepared(image);setPreview(URL.createObjectURL(file));setFileName(file.name);setResult(null);setShowLooks(false);setAlternatives(false);}catch(error){setError(error instanceof Error?error.message:"Could not prepare this image.");}finally{setBusy(false);}}
 async function analyze(){if(!prepared||!data||busy)return;setBusy(true);setError("");try{const analysis=await postJson<ShopAnalysis>("/api/shop",{image:prepared,closet:data.closet,events:data.events,interactions:data.interactions.slice(-100),fallbackItem:{category,color:color.trim()||"unknown",secondaryColors:[],style:style.split(",").map(s=>s.trim()).filter(Boolean),material:"unknown",pattern:"unknown",formality,silhouette:"unknown"}});const next:ShoppingResult={id:crypto.randomUUID(),category:analysis.item.category,verdict:analysis.verdict==="buy"?"BUY":"SKIP",match:analysis.wardrobeImpact,date:new Date().toISOString(),analysis};setResult(next);setShowLooks(false);setAlternatives(false);saveShopping(next);}catch(error){setError(error instanceof Error?error.message:"Analysis could not finish. Please try again.");}finally{setBusy(false);}}
 const analysis=result?.analysis;
 const similar=analysis?.similarGarmentIds.flatMap(id=>data?.closet.find(g=>g.id===id)??[])??[];
 function photo(className:string){return <div className={`relative overflow-hidden rounded-3xl bg-[#eeece6] ${className}`}>{preview?<Image src={preview} alt={`Potential purchase: ${fileName}`} fill unoptimized className="object-contain" onError={()=>setError("This photo could not be displayed. Please choose another JPG or PNG.")}/>:<div className="flex h-full flex-col items-center justify-center gap-4 p-5 text-center text-stone-500"><svg width="48" height="48" viewBox="0 0 48 48" fill="none" stroke="currentColor" strokeWidth="1.3" aria-hidden="true"><rect x="5" y="12" width="38" height="28" rx="6"/><path d="m15 12 3-6h12l3 6"/><circle cx="24" cy="26" r="8"/></svg><p className="eyebrow">Your potential purchase</p></div>}</div>;}
 return <PageShell label="Shopping buddy" title="Before you buy it," subtitle="Ask your closet." aside={<span className="demo-label">✦ {result?sourceLabel(analysis):"Photo analysis + wardrobe context"}</span>}>
  {!result?<div className="grid gap-7 lg:grid-cols-[1.2fr_1fr]">
   <div onDragOver={e=>{e.preventDefault();if(!busy)setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(!busy)void accept(e.dataTransfer.files[0]);}} className={`rounded-[2rem] border border-dashed p-6 sm:p-10 ${dragging?"border-stone-900 bg-stone-200":"border-stone-300 bg-white"}`}>
    {preview?photo("mx-auto aspect-square max-w-sm"): <div className="flex min-h-64 flex-col items-center justify-center"><svg width="56" height="56" viewBox="0 0 48 48" fill="none" stroke="currentColor" strokeWidth="1.2" aria-hidden="true"><rect x="6" y="8" width="36" height="32" rx="6"/><circle cx="17" cy="18" r="3"/><path d="m7 34 12-11 9 9 7-6 7 8"/></svg><h2 className="mt-7 font-serif text-4xl">Drop a photo.</h2><p className="mt-3 text-sm text-stone-500">A second opinion, before checkout.</p></div>}
    <div className="mt-6 flex flex-wrap justify-center gap-3"><button disabled={busy} onClick={()=>upload.current?.click()} className="btn-primary">{preview?"Change photo":"Choose photo"} ↗</button><button disabled={busy} onClick={()=>camera.current?.click()} className="btn-secondary">Take a photo</button></div><p className="mt-5 text-center text-[10px] text-stone-500">JPG, PNG, WebP · Up to 10 MB · Photo is sent to the server for analysis; not saved to history</p>
   </div>
   <div className="flex flex-col justify-center rounded-[2rem] bg-[#eae6dc] p-7 sm:p-10"><p className="eyebrow">Buy better, not more</p><h2 className="mt-6 font-serif text-4xl leading-tight tracking-tight">Does it earn<br/>its closet space?</h2><p className="mt-5 text-sm leading-7 text-stone-600">A great piece works with your life, your style, and what’s already hanging in your closet.</p><label className="eyebrow mt-7">Item category<select disabled={busy} value={category} onChange={e=>setCategory(e.target.value as GarmentCategory)} className="mt-3 block w-full rounded-xl bg-white p-4 text-sm normal-case tracking-normal text-stone-900">{categories.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="mt-5 grid grid-cols-2 gap-3"><label className="eyebrow">Color<input disabled={busy} value={color} onChange={e=>setColor(e.target.value)} maxLength={100} className="mt-2 w-full rounded-xl bg-white p-3 text-sm normal-case tracking-normal"/></label><label className="eyebrow">Formality<select disabled={busy} value={formality} onChange={e=>setFormality(e.target.value as GarmentFormality)} className="mt-2 w-full rounded-xl bg-white p-3 text-sm normal-case tracking-normal">{["casual","smart-casual","professional","dressy","formal"].map(f=><option key={f}>{f}</option>)}</select></label></div><label className="eyebrow mt-4">Style tags<input disabled={busy} value={style} onChange={e=>setStyle(e.target.value)} maxLength={200} className="mt-2 w-full rounded-xl bg-white p-3 text-sm normal-case tracking-normal"/></label><p className="mt-5 text-xs leading-6 text-stone-500">Gemini analyzes the photo when available. These item details are used if AI is unavailable. Scores are explainable product heuristics, not scientific measurements.</p><div className="mt-4 flex flex-wrap gap-3"><button disabled={busy||!prepared} onClick={analyze} className="btn-primary">{busy?"Working…":"Analyze wardrobe impact"}</button></div></div>
  </div>:<>
   <button onClick={()=>setResult(null)} className="mb-6 min-h-11 text-xs uppercase tracking-widest">← Check another piece</button>
   <div className="grid gap-7 lg:grid-cols-[.8fr_1.2fr]">{photo("aspect-[4/5] max-h-[600px]")}<div className="rounded-[2rem] bg-white p-7 sm:p-10"><span className="demo-label">{sourceLabel(analysis)} · heuristic scores</span><div className="mt-7 flex flex-wrap items-end justify-between gap-5"><h2 className="font-serif text-8xl tracking-[-.06em]">{result.verdict}</h2><div className="text-right"><p className="font-serif text-5xl">{result.match}%</p><p className="eyebrow mt-2">Wardrobe match</p></div></div><p className="mt-6 font-serif text-2xl leading-snug">{result.verdict==="BUY"?"This item earns its closet space.":"A familiar story. Not a new possibility."}</p><p className="mt-4 text-sm leading-7 text-stone-500">{analysis?.reasoning}</p>
    <div className="mt-7 grid grid-cols-2 gap-x-6 gap-y-5 border-y border-stone-200 py-6">{[["Style match",`${analysis?.styleMatch}%`],["Compatibility",`${analysis?.compatibility}%`],["Redundancy",`${analysis?.redundancy}%`],["Wardrobe need",`${analysis?.wardrobeNeed}%`]].map(([label,value])=><div key={label}><p className="eyebrow">{label}</p><p className="mt-2 font-serif text-3xl">{value}</p></div>)}</div><p className="eyebrow mt-6">Wardrobe impact</p><p className="mt-2 text-sm text-stone-500">{analysis?.wardrobeImpact}/100 · 30% compatibility + 25% style match + 20% uniqueness + 15% wardrobe need + 10% upcoming utility</p><ul className="mt-4 space-y-2 text-xs leading-5 text-stone-500">{analysis?.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>{analysis && analysis.source!=="fallback"&&<p className="mt-3 text-sm leading-6 text-stone-600">{analysis.semanticReasoning}</p>}<p className="mt-3 text-xs text-stone-500">{analysis?.notice}</p><button onClick={()=>result.verdict==="BUY"?setShowLooks(!showLooks):setAlternatives(!alternatives)} className="btn-primary mt-7 w-full">{result.verdict==="BUY"?"Show me how I’d wear it":"Show me what I should buy instead"} ↗</button>
   </div></div>
   {result.verdict==="SKIP"&&<section className="mt-12"><p className="eyebrow">Similar items you own</p><h2 className="mt-3 font-serif text-3xl">Start with your own closet.</h2><p className="mt-3 text-xs text-stone-500">Close functional matches based on category, color, formality, pattern, and style.</p><div className="mt-5 grid max-w-xl grid-cols-2 gap-4">{similar.map(g=><div key={g.id}><GarmentImage garment={g} className="aspect-square"/><p className="mt-3 text-sm">{g.name}</p></div>)}</div>{!similar.length&&<p className="mt-5 text-sm">No close duplicates were found. Other factors reduced this item’s added utility.</p>}</section>}
   {alternatives&&<section className="mt-10 rounded-3xl bg-white p-7"><p className="eyebrow">A more considered next step</p><h2 className="mt-3 font-serif text-3xl">Try what you own first.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-stone-500">Restyle an existing piece for your next event. If you still notice a gap, look for a neutral, comfortable layer that pairs with at least three outfits you love.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/fits" className="btn-primary">Explore my fits</Link><button onClick={()=>setResult(null)} className="btn-secondary">Evaluate another item</button></div></section>}
   {showLooks&&<section className="mt-12"><p className="eyebrow">{analysis?.outfits.length??0} ways to wear it / your candidate stays fixed</p><h2 className="mt-3 font-serif text-4xl">New piece. Familiar favorites.</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{analysis?.outfits.map((outfit,index)=><article key={index} className="rounded-3xl bg-white p-5"><h3 className="font-serif text-2xl">Look {index+1}</h3><div className="mt-4 grid grid-cols-2 gap-2">{outfit.garmentIds.map(id=>{if(id===CANDIDATE_ID)return <div key={id}>{photo("aspect-square")}<p className="mt-1 text-[10px]">Your candidate · locked</p></div>;const garment=data?.closet.find(g=>g.id===id);return garment?<GarmentImage key={id} garment={garment} className="aspect-square"/>:null;})}</div><p className="mt-4 text-xs leading-5 text-stone-500">{outfit.reasoning}</p></article>)}</div>{!analysis?.outfits.length&&<p className="mt-5 text-sm">There are not enough complementary active garments to make a complete outfit.</p>}</section>}
  </>}
  <input ref={upload} aria-label="Upload a purchase photo" type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>{accept(e.target.files?.[0]);e.target.value="";}}/><input ref={camera} aria-label="Take a purchase photo" type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>{accept(e.target.files?.[0]);e.target.value="";}}/>
  <p role="status" className="mt-5 text-sm text-stone-600">{busy?"Preparing or analyzing your photo… this may take up to 25 seconds.":error}</p>
  {!!data?.shopping.length&&<p className="mt-8 text-xs text-stone-500">{data.shopping.length} wardrobe {data.shopping.length===1?"check":"checks"} saved on this device. Uploaded photos are not saved to history.</p>}
 </PageShell>;
}
